# OAuth2 Resource Server Configuration
spring.security.oauth2.resourceserver.opaque-token.introspection-uri=https://www.googleapis.com/
spring.security.oauth2.resourceserver.opaque-token.clientId=${GOOGLE_CLIENT_ID}
spring.security.oauth2.resourceserver.opaque-token.clientSecret=${GOOGLE_CLIENT_SECRET}

  # MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/data-collecting-db

  # Kafka Configuration
spring.kafka.bootstrap-servers=34.116.223.113:9094
#spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER}
spring.kafka.sasl.username=user1
#spring.kafka.sasl.username=${KAFKA_USERNAME}
spring.kafka.sasl.password=MRbDIo75MI
#spring.kafka.sasl.password=${KAFKA_PASSWORD}

  # Server Configuration
server.port=8085

  # Application Configuration
app.frontend.url=${FRONTEND_URL:http://localhost:4200}

  # Logging Levels
logging.level.org.springframework.web.cors=TRACE
logging.level.org.springframework.security=TRACE
