apiVersion: v1
kind: Service
metadata:
  name: java-server
  labels:
    app: java-server
spec:
  type: LoadBalancer
  selector:
    app: java-server
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
